# Generated by Django 3.2.7 on 2021-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('etiquette', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
            ],
        ),
    ]
