# Generated by Django 3.2.7 on 2021-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialreason', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('postale', models.CharField(max_length=255)),
                ('devise', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=255, upload_to='storage/images/params/')),
                ('allow_waiting_payment', models.BooleanField(default=True)),
                ('tva', models.BooleanField(default=True)),
                ('seuil_credit', models.BooleanField(default=True)),
                ('production_auto', models.BooleanField(default=True)),
                ('rupture_stock', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('fabrique', 'Peut acceder à la gestion de la fabrique'), ('boutique', 'Peut acceder à la gestion de la boutique'), ('production', 'Peut acceder à la gestion de la production'), ('organisation', "Peut acceder à la gestion de l'organisation"), ('commande', 'Peut acceder à la gestion des commande'), ('approvisionnement', 'Peut acceder à la gestion des approvisionnement'), ('comptabilitte', 'Peut acceder à la gestion des comptabilitte'), ('configuration', 'Peut acceder aux configurations'), ('role', 'Peut acceder aux accès utilisateurs')],
            },
        ),
        migrations.CreateModel(
            name='MyCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField(default='')),
                ('tentative', models.IntegerField(default=3)),
            ],
        ),
    ]
