# Generated by Django 3.2.7 on 2021-09-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=255)),
                ('expired', models.CharField(max_length=255)),
                ('tentative', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contatct', models.IntegerField(max_length=255)),
                ('fax', models.IntegerField(max_length=255)),
                ('postale', models.IntegerField(max_length=255)),
                ('devise', models.IntegerField(max_length=255)),
                ('allow_waiting_payment', models.BooleanField(default=True)),
                ('tva', models.BooleanField(default=True)),
                ('seuil_credit', models.BooleanField(default=True)),
                ('production_auto', models.BooleanField(default=True)),
                ('rupture_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
