# Generated by Django 3.2.7 on 2021-09-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Params',
            new_name='MyApp',
        ),
        migrations.AlterModelOptions(
            name='myapp',
            options={'permissions': [('production', 'Peut acceder à la gestion de la production'), ('organisation', "Peut acceder à la gestion de l'organisation"), ('commande', 'Peut acceder à la gestion des commande'), ('approvisionnement', 'Peut acceder à la gestion des approvisionnement'), ('comptabilitte', 'Peut acceder à la gestion des comptabilitte'), ('configuration', 'Peut acceder aux configurations'), ('role', 'Peut acceder aux accès utilisateurs')]},
        ),
    ]
