# Generated by Django 4.0.4 on 2022-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='devise',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='postale',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
