# Generated by Django 3.2.7 on 2021-09-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='params',
            old_name='societe',
            new_name='socialreason',
        ),
    ]
