# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='production_auto',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='rupture_stock',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='seuil_credit',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='tva',
        ),
    ]
