# Generated by Django 3.2.7 on 2021-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0002_rename_societe_params_socialreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompte',
            name='expired',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mycompte',
            name='tentative',
            field=models.IntegerField(default=3),
        ),
    ]
