# Generated by Django 3.2.8 on 2021-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0002_auto_20211020_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='production_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myapp',
            name='seuil_credit',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='myapp',
            name='tva',
            field=models.IntegerField(default=True),
        ),
    ]
