# Generated by Django 3.2.7 on 2021-09-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0002_auto_20210929_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'permissions': [('fabrique', 'Peut acceder à la gestion de la fabrique'), ('boutique', 'Peut acceder à la gestion de la boutique'), ('production', 'Peut acceder à la gestion de la production'), ('organisation', "Peut acceder à la gestion de l'organisation"), ('commande', 'Peut acceder à la gestion des commande'), ('approvisionnement', 'Peut acceder à la gestion des approvisionnement'), ('comptabilitte', 'Peut acceder à la gestion des comptabilitte'), ('configuration', 'Peut acceder aux configurations'), ('role', 'Peut acceder aux accès utilisateurs')]},
        ),
        migrations.RenameField(
            model_name='mycompte',
            old_name='expired',
            new_name='expiration',
        ),
    ]
