# Generated by Django 3.2.7 on 2021-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0003_auto_20210929_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='devise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='params',
            name='fax',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='params',
            name='postale',
            field=models.CharField(max_length=255),
        ),
    ]
