# Generated by Django 3.2.8 on 2021-10-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0003_auto_20211020_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='devise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='postale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='seuil_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='tva',
            field=models.IntegerField(default=0),
        ),
    ]
