# Generated by Django 3.2.8 on 2021-10-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0004_auto_20211030_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
