# Generated by Django 3.2.7 on 2021-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0004_auto_20210929_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='contatct',
        ),
        migrations.AddField(
            model_name='params',
            name='contact',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
