# Generated by Django 3.2.7 on 2021-09-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0005_auto_20210929_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='logo',
            field=models.ImageField(default=' ', max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
