# Generated by Django 3.2.8 on 2021-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0005_myapp_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='allow_waiting_payment',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='production_auto',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='seuil_credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='tva',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
