# Generated by Django 3.2.8 on 2021-10-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paramApp', '0006_auto_20211031_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'permissions': [('fabrique', 'BRICX | Peut acceder à la gestion de la fabrique'), ('boutique', 'BRICX | Peut acceder à la gestion de la boutique'), ('production', 'BRICX | Peut acceder à la gestion de la production'), ('organisation', "BRICX | Peut acceder à la gestion de l'organisation"), ('commande', 'BRICX | Peut acceder à la gestion des commande'), ('livraisons', 'BRICX | Peut acceder à la gestion des livraisons'), ('approvisionnement', 'BRICX | Peut acceder à la gestion des approvisionnement'), ('comptabilitte', 'BRICX | Peut acceder à la gestion des comptabilitte'), ('tresorerie', 'BRICX | Peut acceder à la tresorerie'), ('administration', 'BRICX | Peut acceder aux administrations'), ('role', 'BRICX | Peut acceder aux accès utilisateurs')]},
        ),
    ]
