# Generated by Django 3.2.8 on 2021-10-15 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('comment', models.TextField(default='')),
                ('datelivraison', models.DateTimeField(blank=True, null=True)),
                ('nom_receptionniste', models.CharField(default='', max_length=255)),
                ('contact_receptionniste', models.CharField(default='', max_length=255)),
                ('chargement', models.BooleanField(default=True)),
                ('dechargement', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('immatriculation', models.CharField(max_length=255)),
                ('modele', models.CharField(blank=True, max_length=255, null=True)),
                ('marque', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('montant', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_tricycle', to='livraisonApp.livraison')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
