# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lignelivraison',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tricycle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['-created_at']},
        ),
    ]
