# Generated by Django 3.2.9 on 2021-11-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['etat__etiquette', '-created_at']},
        ),
        migrations.AlterField(
            model_name='livraison',
            name='contact_receptionniste',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='nom_receptionniste',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
