# Generated by Django 3.2.8 on 2021-10-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0004_modelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='modelivraison',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mode_livraison', to='livraisonApp.modelivraison'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_livraison', to='livraisonApp.chauffeur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_livraison', to='livraisonApp.vehicule'),
        ),
    ]
