# Generated by Django 3.2.8 on 2021-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0005_auto_20211022_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelivraison',
            options={'ordering': ['etiquette']},
        ),
        migrations.RenameField(
            model_name='lignelivraison',
            old_name='price',
            new_name='reste',
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='perte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='surplus',
            field=models.IntegerField(default=0),
        ),
    ]
