# Generated by Django 3.2.8 on 2021-10-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0007_alter_commande_comment'),
        ('livraisonApp', '0006_auto_20211022_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='zone_livraison', to='commandeApp.zonelivraison'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
