# Generated by Django 3.2.8 on 2021-10-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0007_auto_20211025_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignelivraison',
            name='livree',
            field=models.IntegerField(default=0),
        ),
    ]
