# Generated by Django 3.2.8 on 2021-10-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonApp', '0008_lignelivraison_livree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tricycle',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='etat',
        ),
    ]
