# Generated by Django 3.2.8 on 2021-10-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeclient',
            name='etiquette',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
