# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_typeclient_etiquette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'ordering': ['-created_at']},
        ),
    ]
