# Generated by Django 3.2.8 on 2021-10-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_auto_20211020_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
