# Generated by Django 3.2.7 on 2021-09-29 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '__first__'),
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField(default='')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExigenceProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_exigenceproduction', to='productionApp.brique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField(default='')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('etiquette', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=255)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_transfertstock', to='organisationApp.agence')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_transfertstock', to='organisationApp.employe')),
                ('groupecommande_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_groupecommande_transfertstock', to='productionApp.brique')),
                ('groupecommande_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_groupecommande_transfertstock', to='productionApp.brique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_rangement', models.DateTimeField(blank=True, null=True)),
                ('montant_production', models.IntegerField(default=0)),
                ('montant_rangement', models.IntegerField(default=0)),
                ('montant_livraison', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_production', to='organisationApp.agence')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_production', to='organisationApp.employe')),
                ('employe_rangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_rangement_production', to='organisationApp.employe')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerteRessource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_perteressource', to='organisationApp.agence')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_perteressource', to='organisationApp.employe')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_perte', to='productionApp.ressource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_perteressource', to='productionApp.typeperte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerteBrique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_perte', to='organisationApp.agence')),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_perte', to='productionApp.brique')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_pertebrique', to='organisationApp.employe')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_pertebrique', to='productionApp.typeperte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayeBriqueFerie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('price_rangement', models.IntegerField(default=0)),
                ('price_livraison', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_payeferie', to='productionApp.brique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayeBrique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('price_rangement', models.IntegerField(default=0)),
                ('price_livraison', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_paye', to='productionApp.brique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneTransfertStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite_avant', models.IntegerField(default=0)),
                ('quantite_apres', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_transfertligne', to='productionApp.brique')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_ligne', to='productionApp.transfertstock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('perte', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_ligneproduction', to='productionApp.brique')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_ligne', to='productionApp.production')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LignePerteBrique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_perteligne', to='productionApp.brique')),
                ('perte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perte_ligne', to='productionApp.pertebrique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneExigenceProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigence_ligne', to='productionApp.exigenceproduction')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_exigenceligne', to='productionApp.ressource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneConsommation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_ligneconsommation', to='productionApp.production')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_ligneconsommation', to='productionApp.ressource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialRessourceAgence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_initialressource', to='organisationApp.agence')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource_initialagence', to='productionApp.ressource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialBriqueAgence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_initialbrique', to='organisationApp.agence')),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_initialagence', to='productionApp.brique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsommationJour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('date', models.DateField(default='')),
                ('comment', models.TextField(default='')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_consommationjour', to='organisationApp.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
