# Generated by Django 3.2.9 on 2021-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneconsommation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
