# Generated by Django 3.2.7 on 2021-09-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brique',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='is_active',
            new_name='active',
        ),
    ]
