# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brique',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='consommationjour',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='exigenceproduction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='initialbriqueagence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='initialressourceagence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ligneconsommation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ligneexigenceproduction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lignepertebrique',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ligneproduction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lignetransfertstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payebrique',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payebriqueferie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pertebrique',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='perteressource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ressource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transfertstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='typeperte',
            options={'ordering': ['-created_at']},
        ),
    ]
