# Generated by Django 3.2.8 on 2021-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0002_auto_20211020_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='brique',
            name='alert_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ressource',
            name='alert_stock',
            field=models.IntegerField(default=10),
        ),
    ]
