# Generated by Django 3.2.8 on 2021-10-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0003_auto_20211020_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertstock',
            name='agence',
        ),
        migrations.RemoveField(
            model_name='transfertstock',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='transfertstock',
            name='groupecommande_new',
        ),
        migrations.RemoveField(
            model_name='transfertstock',
            name='groupecommande_old',
        ),
        migrations.DeleteModel(
            name='LigneTransfertStock',
        ),
        migrations.DeleteModel(
            name='TransfertStock',
        ),
    ]
