# Generated by Django 3.2.8 on 2021-10-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0005_ressource_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertebrique',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='perteressource',
            name='etat',
        ),
    ]
