# Generated by Django 3.2.8 on 2021-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0006_auto_20211024_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertebrique',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='perteressource',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
