# Generated by Django 3.2.8 on 2021-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0007_auto_20211024_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertebrique',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='perteressource',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='LignePerteBrique',
        ),
    ]
