# Generated by Django 3.2.8 on 2021-10-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0008_auto_20211025_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeperte',
            name='etiquette',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
