# Generated by Django 3.2.8 on 2021-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0009_alter_typeperte_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
