# Generated by Django 3.2.8 on 2021-10-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionApp', '0010_ressource_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brique',
            name='alert_stock',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='alert_stock',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
