# Generated by Django 3.2.7 on 2021-09-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='employe',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
