# Generated by Django 3.2.7 on 2021-09-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0001_initial'),
        ('organisationApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_role', to='organisationApp.employe'),
        ),
        migrations.AddField(
            model_name='roleemploye',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_acces', to='authApp.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_forgotpassword', to='organisationApp.employe'),
        ),
        migrations.AddField(
            model_name='accesagence',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_acces', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='accesagence',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_acces', to='organisationApp.employe'),
        ),
    ]
