# Generated by Django 3.2.8 on 2021-11-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0001_initial'),
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesagence',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_acces', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='accesagence',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_acces', to='organisationApp.employe'),
        ),
    ]
