# Generated by Django 4.0.4 on 2022-07-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisationApp', '0001_initial'),
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesagence',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_acces', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='accesagence',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_acces', to='organisationApp.employe'),
        ),
    ]
