# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesagence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='forgotpassword',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='forgotpassword',
            name='employe',
        ),
    ]
