# Generated by Django 3.2.7 on 2021-09-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_role_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleemploye',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='roleemploye',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleEmploye',
        ),
    ]
