# Generated by Django 4.0.4 on 2022-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=255, null=True, upload_to='stockage/images/employes/'),
        ),
    ]
