# Generated by Django 3.2.9 on 2021-11-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
