# Generated by Django 3.2.7 on 2021-09-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
