# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'ordering': ['-created_at']},
        ),
    ]
