# Generated by Django 3.2.8 on 2021-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='storage/images/employes/'),
        ),
    ]
