# Generated by Django 3.2.9 on 2021-11-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0002_employe_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='brut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
