# Generated by Django 3.2.8 on 2021-10-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilityApp', '0003_auto_20211016_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='reference',
        ),
        migrations.AlterField(
            model_name='operation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
