# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilityApp', '0004_auto_20211016_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoperation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='compteclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='modepayement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mouvement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reglementachatstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reglementapprovisionnement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reglementcommande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reglementtricycle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transfertfond',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='typemouvement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='typeoperationcaisse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='typereglement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='categoryoperation',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoperation',
            name='etiquette',
            field=models.CharField(max_length=255),
        ),
    ]
