# Generated by Django 3.2.8 on 2021-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilityApp', '0005_auto_20211020_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modepayement',
            options={'ordering': ['etiquette']},
        ),
        migrations.AddField(
            model_name='reglementachatstock',
            name='restait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reglementapprovisionnement',
            name='restait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reglementcommande',
            name='restait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reglementtricycle',
            name='restait',
            field=models.IntegerField(default=0),
        ),
    ]
