# Generated by Django 3.2.8 on 2021-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilityApp', '0006_auto_20211021_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='transfertfond',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
