# Generated by Django 3.2.8 on 2021-10-27 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0007_rename_logo_fournisseur_image'),
        ('comptabilityApp', '0007_auto_20211025_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('is_dette', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_compte', to='approvisionnementApp.fournisseur')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvement_comptefournisseur', to='comptabilityApp.mouvement')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
