# Generated by Django 3.2.8 on 2021-10-29 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0002_alter_agence_options'),
        ('comptabilityApp', '0008_comptefournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_compte', to='organisationApp.agence'),
        ),
    ]
