# Generated by Django 3.2.8 on 2021-10-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilityApp', '0009_alter_compte_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='date_approbation',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
