# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='approvisionnement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ligneachatstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ligneapprovisionnement',
            options={'ordering': ['-created_at']},
        ),
    ]
