# Generated by Django 4.0.4 on 2022-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0003_auto_20211207_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=255, null=True, upload_to='stockage/images/fournisseurs/'),
        ),
    ]
