# Generated by Django 3.2.8 on 2021-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0004_auto_20211025_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='storage/images/fournisseurs/'),
        ),
    ]
