# Generated by Django 3.2.8 on 2021-10-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0005_fournisseur_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='seuil_credit',
        ),
    ]
