# Generated by Django 3.2.8 on 2021-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnementApp', '0007_rename_logo_fournisseur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatstock',
            name='transport',
            field=models.IntegerField(default=0),
        ),
    ]
