# Generated by Django 3.2.8 on 2021-10-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0002_alter_agence_options'),
        ('approvisionnementApp', '0008_achatstock_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatstock',
            name='employe_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_reception_achatstock', to='organisationApp.employe'),
        ),
    ]
