# Generated by Django 3.2.9 on 2021-11-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['deleted', '-created_at']},
        ),
    ]
