# Generated by Django 3.2.7 on 2021-09-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productionApp', '0001_initial'),
        ('coreApp', '__first__'),
        ('organisationApp', '0001_initial'),
        ('commandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prixzonelivraison',
            name='brique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_zoneprix', to='productionApp.brique'),
        ),
        migrations.AddField(
            model_name='prixzonelivraison',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_prix', to='commandeApp.zonelivraison'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_livraison', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_livraison', to='commandeApp.chauffeur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_livraison', to='organisationApp.employe'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='groupecommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupecommande_livraison', to='commandeApp.groupecommande'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_livraison', to='commandeApp.vehicule'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='zonelivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_livraison', to='commandeApp.zonelivraison'),
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='brique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_lignelivraison', to='productionApp.brique'),
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_ligne', to='commandeApp.livraison'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='brique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_lignecommande', to='productionApp.brique'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_ligne', to='commandeApp.commande'),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_groupecommande', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_groupecommande', to='commandeApp.client'),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat'),
        ),
        migrations.AddField(
            model_name='commande',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_commande', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='commande',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_commande', to='organisationApp.employe'),
        ),
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat'),
        ),
        migrations.AddField(
            model_name='commande',
            name='groupecommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_groupecommande', to='commandeApp.groupecommande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='zonelivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_commande', to='commandeApp.zonelivraison'),
        ),
        migrations.AddField(
            model_name='client',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_agence', to='organisationApp.agence'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_client', to='commandeApp.typeclient'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.etat'),
        ),
    ]
