# Generated by Django 3.2.8 on 2021-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupecommande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prixzonelivraison',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='zonelivraison',
            options={'ordering': ['-created_at']},
        ),
    ]
