# Generated by Django 3.2.8 on 2021-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupecommande',
            name='datelivraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
