# Generated by Django 3.2.9 on 2021-11-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupecommande',
            name='is_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='acompte_client',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='avance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='datelivraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dette_client',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='taux_tva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tva',
            field=models.FloatField(default=0),
        ),
    ]
