# Generated by Django 3.2.9 on 2021-11-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0003_auto_20211115_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupecommande',
            name='is_conversion',
        ),
        migrations.AddField(
            model_name='commande',
            name='is_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
