# Generated by Django 3.2.8 on 2021-10-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0003_auto_20211020_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='acompteFournisseur',
            new_name='acompte_client',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='detteFournisseur',
            new_name='dette_client',
        ),
    ]
