# Generated by Django 3.2.8 on 2021-10-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0004_auto_20211020_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='zonelivraison',
            new_name='zone',
        ),
    ]
