# Generated by Django 3.2.9 on 2021-12-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandeApp', '0004_auto_20211115_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='reference',
        ),
    ]
