# Generated by Django 3.2.8 on 2021-10-21 21:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisationApp', '0002_alter_agence_options'),
        ('productionApp', '0004_auto_20211021_2152'),
        ('commandeApp', '0005_rename_zonelivraison_commande_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=255)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_conversion', to='organisationApp.agence')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_transfertstock', to='organisationApp.employe')),
                ('groupecommande_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_groupecommande_conversion', to='commandeApp.groupecommande')),
                ('groupecommande_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_groupecommande_conversion', to='commandeApp.groupecommande')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('quantite_avant', models.IntegerField(default=0)),
                ('quantite_apres', models.IntegerField(default=0)),
                ('brique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brique_conversionligne', to='productionApp.brique')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_ligne', to='commandeApp.conversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
